CREATE TABLE `activity_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`action` varchar(100) NOT NULL,
	`actionCategory` varchar(50) NOT NULL,
	`details` json,
	`ipAddress` varchar(45),
	`userAgent` text,
	`referrer` text,
	`pagePath` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `activity_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_advisor_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cacheType` enum('property','market') NOT NULL,
	`cacheKey` varchar(255) NOT NULL,
	`address` text,
	`city` varchar(255),
	`state` varchar(100),
	`zipCode` varchar(20),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`marketName` varchar(255),
	`inputHash` varchar(64),
	`advice` text NOT NULL,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp NOT NULL,
	`hitCount` int NOT NULL DEFAULT 0,
	`lastAccessedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_advisor_cache_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `analysis_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`address` text NOT NULL,
	`city` varchar(255),
	`state` varchar(100),
	`zipCode` varchar(20),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`monthlyRent` int,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`annualRevenueConservative` int,
	`annualRevenueRealistic` int,
	`annualRevenueOptimistic` int,
	`occupancyRate` decimal(5,2),
	`averageDailyRate` int,
	`revpar` int,
	`annualProfitConservative` int,
	`annualProfitRealistic` int,
	`annualProfitOptimistic` int,
	`breakEvenOccupancy` decimal(5,2),
	`startupCostsMin` int,
	`startupCostsMax` int,
	`verdict` varchar(50),
	`confidenceScore` int,
	`fullAnalysisData` json,
	`narrativeReport` json,
	`competitorData` json,
	`leadName` varchar(255),
	`leadEmail` varchar(320),
	`leadPhone` varchar(50),
	`userIp` varchar(45),
	`userAgent` text,
	`sessionId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `analysis_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `browser_use_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settingKey` varchar(100) NOT NULL,
	`settingValue` text NOT NULL,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `browser_use_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `browser_use_settings_settingKey_unique` UNIQUE(`settingKey`)
);
--> statement-breakpoint
CREATE TABLE `deep_analysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportId` int NOT NULL,
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`currentStep` varchar(100),
	`completedSteps` json,
	`errorMessage` text,
	`historicalContext` json,
	`investmentThesis` json,
	`riskNarrative` json,
	`pricingStrategy` json,
	`competitorPhotoAnalysis` json,
	`executiveSummaryEnhanced` text,
	`marketNarrative` text,
	`actionPlan` json,
	`processingTimeMs` int,
	`aiProvider` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `deep_analysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `favorite_markets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`marketId` varchar(64) NOT NULL,
	`marketName` varchar(255) NOT NULL,
	`marketType` varchar(100),
	`state` varchar(100),
	`country` varchar(100),
	`marketScore` decimal(5,2),
	`listingCount` int,
	`averageRevenue` int,
	`averageOccupancy` decimal(5,2),
	`averageAdr` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `favorite_markets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `favorite_properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`address` text NOT NULL,
	`city` varchar(255),
	`state` varchar(100),
	`zipCode` varchar(20),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`propertyType` varchar(100),
	`marketId` varchar(64),
	`marketName` varchar(255),
	`annualRevenue` int,
	`monthlyRevenue` int,
	`occupancyRate` decimal(5,2),
	`averageDailyRate` int,
	`monthlyRent` int,
	`estimatedProfit` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `favorite_properties_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`address` text NOT NULL,
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`accommodates` int,
	`zillowUrl` text,
	`annualRevenue` int,
	`averageDailyRate` int,
	`occupancyRate` decimal(5,2),
	`marketId` varchar(64),
	`marketName` varchar(255),
	`status` enum('new','contacted','qualified','converted','closed') NOT NULL DEFAULT 'new',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`email` varchar(320) NOT NULL,
	`marketId` varchar(64) NOT NULL,
	`marketName` varchar(255) NOT NULL,
	`alertType` enum('revenue_change','occupancy_change','adr_change','all_changes') NOT NULL DEFAULT 'all_changes',
	`thresholdPercent` int NOT NULL DEFAULT 10,
	`baselineRevenue` int,
	`baselineOccupancy` decimal(5,2),
	`baselineAdr` int,
	`isActive` enum('true','false') NOT NULL DEFAULT 'true',
	`lastCheckedAt` timestamp,
	`lastAlertSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `market_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_research_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`researchId` varchar(100) NOT NULL,
	`market` varchar(255) NOT NULL,
	`status` enum('pending','running','completed','error') NOT NULL DEFAULT 'pending',
	`progress` int DEFAULT 0,
	`currentStep` varchar(255),
	`errorMessage` text,
	`sessionId` varchar(100),
	`taskId` varchar(100),
	`result` json,
	`userId` int,
	`sessionToken` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `market_research_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `market_research_reports_researchId_unique` UNIQUE(`researchId`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`type` enum('report_generated','system','alert','info') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`metadata` json,
	`isRead` int NOT NULL DEFAULT 0,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `opportunity_searches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`searchId` varchar(100) NOT NULL,
	`city` varchar(255) NOT NULL,
	`minRent` int,
	`maxRent` int,
	`status` enum('pending','running','completed','error') NOT NULL DEFAULT 'pending',
	`progress` int DEFAULT 0,
	`currentStep` varchar(255),
	`errorMessage` text,
	`zillowTaskId` varchar(100),
	`amenityTaskId` varchar(100),
	`marketSnapshot` json,
	`winningAmenities` json,
	`opportunities` json,
	`userId` int,
	`sessionToken` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `opportunity_searches_id` PRIMARY KEY(`id`),
	CONSTRAINT `opportunity_searches_searchId_unique` UNIQUE(`searchId`)
);
--> statement-breakpoint
CREATE TABLE `owner_notification_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`notificationType` enum('property_report','market_report','lead_capture','system') NOT NULL,
	`reportId` int,
	`title` varchar(255) NOT NULL,
	`summary` text,
	`triggeredByIp` varchar(45),
	`triggeredByUserId` int,
	`deliveryStatus` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
	`deliveredAt` timestamp,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `owner_notification_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `property_images` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` varchar(100) NOT NULL,
	`platform` varchar(50),
	`images` json NOT NULL,
	`imageCount` int NOT NULL,
	`fetchedAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `property_images_id` PRIMARY KEY(`id`),
	CONSTRAINT `property_images_propertyId_unique` UNIQUE(`propertyId`)
);
--> statement-breakpoint
CREATE TABLE `saved_searches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`searchType` enum('market','property') NOT NULL,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`submarketId` varchar(64),
	`submarketName` varchar(255),
	`address` text,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`cachedRevenue` int,
	`cachedOccupancy` decimal(5,2),
	`cachedAdr` int,
	`label` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `saved_searches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shared_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shareId` varchar(32) NOT NULL,
	`reportType` enum('property','market') NOT NULL,
	`address` text,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`accommodates` int,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`submarketId` varchar(64),
	`submarketName` varchar(255),
	`reportData` text,
	`createdByUserId` int,
	`createdByName` varchar(255),
	`expiresAt` timestamp,
	`viewCount` int NOT NULL DEFAULT 0,
	`maxViews` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shared_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `shared_reports_shareId_unique` UNIQUE(`shareId`)
);
--> statement-breakpoint
CREATE TABLE `user_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64) NOT NULL,
	`ipAddress` varchar(45),
	`userAgent` text,
	`country` varchar(100),
	`city` varchar(255),
	`pageViews` int DEFAULT 0,
	`actionsCount` int DEFAULT 0,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`lastActivityAt` timestamp NOT NULL DEFAULT (now()),
	`endedAt` timestamp,
	CONSTRAINT `user_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_sessions_sessionId_unique` UNIQUE(`sessionId`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`phone` varchar(50),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
