CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`address` text NOT NULL,
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`accommodates` int,
	`zillowUrl` text,
	`annualRevenue` int,
	`averageDailyRate` int,
	`occupancyRate` decimal(5,2),
	`marketId` varchar(64),
	`marketName` varchar(255),
	`status` enum('new','contacted','qualified','converted','closed') NOT NULL DEFAULT 'new',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
