CREATE TABLE `saved_searches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`searchType` enum('market','property') NOT NULL,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`submarketId` varchar(64),
	`submarketName` varchar(255),
	`address` text,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`cachedRevenue` int,
	`cachedOccupancy` decimal(5,2),
	`cachedAdr` int,
	`label` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `saved_searches_id` PRIMARY KEY(`id`)
);
