CREATE TABLE `favorite_properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`address` text NOT NULL,
	`city` varchar(255),
	`state` varchar(100),
	`zipCode` varchar(20),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`propertyType` varchar(100),
	`marketId` varchar(64),
	`marketName` varchar(255),
	`annualRevenue` int,
	`monthlyRevenue` int,
	`occupancyRate` decimal(5,2),
	`averageDailyRate` int,
	`monthlyRent` int,
	`estimatedProfit` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `favorite_properties_id` PRIMARY KEY(`id`)
);
