CREATE TABLE `regulation_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`locationKey` varchar(255) NOT NULL,
	`city` varchar(255) NOT NULL,
	`state` varchar(100) NOT NULL,
	`status` varchar(50) NOT NULL,
	`yesNoSummary` text,
	`summary` text,
	`simplifiedSummary` text,
	`keyRequirements` json,
	`permitRequired` int DEFAULT 0,
	`primaryResidenceOnly` int DEFAULT 0,
	`maxNightsPerYear` int,
	`registrationFee` varchar(100),
	`occupancyTax` varchar(100),
	`zoningRestrictions` text,
	`sources` json,
	`confidence` varchar(20),
	`warnings` json,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `regulation_cache_id` PRIMARY KEY(`id`),
	CONSTRAINT `regulation_cache_locationKey_unique` UNIQUE(`locationKey`)
);
