CREATE TABLE `analysis_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`address` text NOT NULL,
	`city` varchar(255),
	`state` varchar(100),
	`zipCode` varchar(20),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`monthlyRent` int,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`annualRevenueConservative` int,
	`annualRevenueRealistic` int,
	`annualRevenueOptimistic` int,
	`occupancyRate` decimal(5,2),
	`averageDailyRate` int,
	`revpar` int,
	`annualProfitConservative` int,
	`annualProfitRealistic` int,
	`annualProfitOptimistic` int,
	`breakEvenOccupancy` decimal(5,2),
	`startupCostsMin` int,
	`startupCostsMax` int,
	`verdict` varchar(50),
	`confidenceScore` int,
	`fullAnalysisData` json,
	`narrativeReport` json,
	`competitorData` json,
	`userIp` varchar(45),
	`userAgent` text,
	`sessionId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `analysis_reports_id` PRIMARY KEY(`id`)
);
