CREATE TABLE `bug_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shareCode` varchar(20) NOT NULL,
	`reporterEmail` varchar(320),
	`reporterName` varchar(255),
	`sessionId` varchar(64),
	`userId` int,
	`title` varchar(500) NOT NULL,
	`description` text,
	`stepsToReproduce` text,
	`expectedBehavior` text,
	`actualBehavior` text,
	`toolName` varchar(100),
	`pagePath` varchar(255),
	`propertyAddress` text,
	`city` varchar(255),
	`state` varchar(100),
	`marketId` varchar(64),
	`browserInfo` text,
	`screenSize` varchar(50),
	`errorMessage` text,
	`consoleErrors` text,
	`screenshotUrl` text,
	`status` enum('new','investigating','in_progress','resolved','wont_fix','duplicate') NOT NULL DEFAULT 'new',
	`priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`resolvedAt` timestamp,
	`resolution` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bug_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `bug_reports_shareCode_unique` UNIQUE(`shareCode`)
);
