CREATE TABLE `shareable_regulation_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shareCode` varchar(20) NOT NULL,
	`city` varchar(255) NOT NULL,
	`state` varchar(100) NOT NULL,
	`locationKey` varchar(255) NOT NULL,
	`status` varchar(50) NOT NULL,
	`yesNoSummary` text,
	`summary` text,
	`permitRequired` int DEFAULT 0,
	`primaryResidenceOnly` int DEFAULT 0,
	`maxNightsPerYear` int,
	`registrationFee` varchar(255),
	`occupancyTax` varchar(100),
	`confidence` varchar(20),
	`fullRegulationData` json,
	`keyRequirements` json,
	`sources` json,
	`creatorEmail` varchar(320),
	`creatorPhone` varchar(50),
	`creatorUserId` int,
	`sessionId` varchar(64),
	`viewCount` int NOT NULL DEFAULT 0,
	`lastViewedAt` timestamp,
	`smsSentTo` varchar(50),
	`smsSentAt` timestamp,
	`emailSentTo` varchar(320),
	`emailSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `shareable_regulation_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `shareable_regulation_reports_shareCode_unique` UNIQUE(`shareCode`)
);
