CREATE TABLE `notification_analytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`notificationType` enum('sms','email') NOT NULL,
	`reportType` enum('regulation','revenue','validator','market','ai_advisor','listings','comparison','map') NOT NULL,
	`shareCode` varchar(20) NOT NULL,
	`recipientPhone` varchar(50),
	`recipientEmail` varchar(320),
	`recipientName` varchar(255),
	`city` varchar(255),
	`state` varchar(100),
	`address` text,
	`status` enum('pending','sent','delivered','failed','opened','clicked') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`openedAt` timestamp,
	`clickedAt` timestamp,
	`isAutoNotification` int DEFAULT 0,
	`triggeredBy` varchar(100),
	`senderUserId` int,
	`sessionId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`sentAt` timestamp,
	CONSTRAINT `notification_analytics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `universal_shareable_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shareCode` varchar(20) NOT NULL,
	`reportType` enum('revenue','validator','market','ai_advisor','listings','comparison','map') NOT NULL,
	`address` text,
	`city` varchar(255),
	`state` varchar(100),
	`zipCode` varchar(20),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`monthlyRent` int,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`reportData` json,
	`title` varchar(500),
	`summary` text,
	`annualRevenue` int,
	`occupancyRate` decimal(5,2),
	`averageDailyRate` int,
	`profitMargin` decimal(5,2),
	`verdict` varchar(50),
	`creatorEmail` varchar(320),
	`creatorPhone` varchar(50),
	`creatorName` varchar(255),
	`creatorUserId` int,
	`sessionId` varchar(64),
	`viewCount` int NOT NULL DEFAULT 0,
	`lastViewedAt` timestamp,
	`smsSentTo` varchar(50),
	`smsSentAt` timestamp,
	`emailSentTo` varchar(320),
	`emailSentAt` timestamp,
	`autoNotificationSent` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `universal_shareable_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `universal_shareable_reports_shareCode_unique` UNIQUE(`shareCode`)
);
