CREATE TABLE `deal_alert_criteria` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`email` varchar(320) NOT NULL,
	`firstName` varchar(100),
	`phone` varchar(20),
	`city` varchar(255) NOT NULL,
	`state` varchar(100) NOT NULL,
	`zipCode` varchar(20),
	`marketId` varchar(64),
	`marketName` varchar(255),
	`analysisType` enum('arbitrage','investment','both') NOT NULL DEFAULT 'arbitrage',
	`minBedrooms` int DEFAULT 1,
	`maxBedrooms` int DEFAULT 5,
	`minBathrooms` decimal(3,1) DEFAULT '1',
	`maxRent` int,
	`maxPurchasePrice` int,
	`propertyTypes` json,
	`minMonthlyProfit` int DEFAULT 500,
	`minProfitMargin` decimal(5,2) DEFAULT '0.15',
	`minDealScore` int DEFAULT 50,
	`minOccupancy` decimal(5,2),
	`notifyEmail` int NOT NULL DEFAULT 1,
	`notifySms` int NOT NULL DEFAULT 0,
	`notifyInApp` int NOT NULL DEFAULT 1,
	`frequency` enum('instant','daily','weekly') NOT NULL DEFAULT 'daily',
	`isActive` int NOT NULL DEFAULT 1,
	`lastScannedAt` timestamp,
	`lastMatchFoundAt` timestamp,
	`totalMatchesFound` int NOT NULL DEFAULT 0,
	`totalAlertsSent` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deal_alert_criteria_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deal_alert_matches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`criteriaId` int NOT NULL,
	`address` text NOT NULL,
	`city` varchar(255) NOT NULL,
	`state` varchar(100) NOT NULL,
	`zipCode` varchar(20),
	`bedrooms` int,
	`bathrooms` decimal(3,1),
	`monthlyRent` int,
	`purchasePrice` int,
	`propertyType` varchar(100),
	`sourceUrl` text,
	`sourcePlatform` varchar(50),
	`imageUrl` text,
	`projectedRevenue` int,
	`projectedAdr` int,
	`projectedOccupancy` decimal(5,2),
	`projectedMonthlyProfit` int,
	`projectedAnnualProfit` int,
	`profitMargin` decimal(5,2),
	`dealScore` int,
	`dealGrade` varchar(2),
	`status` enum('new','notified','viewed','saved','dismissed') NOT NULL DEFAULT 'new',
	`notifiedAt` timestamp,
	`viewedAt` timestamp,
	`discoveredAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `deal_alert_matches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`sessionId` varchar(64),
	`email` varchar(320),
	`city` varchar(255) NOT NULL,
	`state` varchar(100) NOT NULL,
	`marketId` varchar(64),
	`marketName` varchar(255),
	`analysisType` enum('arbitrage','investment','both') NOT NULL DEFAULT 'both',
	`bedrooms` int DEFAULT 3,
	`status` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
	`currentStep` varchar(100),
	`progress` int DEFAULT 0,
	`regulationsData` json,
	`marketOverviewData` json,
	`revenueData` json,
	`compsData` json,
	`topPropertiesData` json,
	`aiMemo` text,
	`marketScore` int,
	`averageRevenue` int,
	`averageOccupancy` decimal(5,2),
	`averageAdr` int,
	`regulationRisk` varchar(20),
	`errorMessage` text,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `market_evaluations_id` PRIMARY KEY(`id`)
);
