ALTER TABLE `comment_votes` ADD CONSTRAINT `comment_votes_user_comment_idx` UNIQUE(`userId`,`commentId`);--> statement-breakpoint
ALTER TABLE `newsletter_cities` ADD CONSTRAINT `newsletter_cities_city_state_idx` UNIQUE(`city`,`state`);--> statement-breakpoint
CREATE INDEX `activity_logs_user_id_idx` ON `activity_logs` (`userId`);--> statement-breakpoint
CREATE INDEX `activity_logs_session_id_idx` ON `activity_logs` (`sessionId`);--> statement-breakpoint
CREATE INDEX `activity_logs_action_idx` ON `activity_logs` (`action`);--> statement-breakpoint
CREATE INDEX `activity_logs_created_at_idx` ON `activity_logs` (`createdAt`);--> statement-breakpoint
CREATE INDEX `ai_advisor_cache_key_idx` ON `ai_advisor_cache` (`cacheKey`);--> statement-breakpoint
CREATE INDEX `ai_advisor_cache_type_idx` ON `ai_advisor_cache` (`cacheType`);--> statement-breakpoint
CREATE INDEX `ai_advisor_cache_expires_idx` ON `ai_advisor_cache` (`expiresAt`);--> statement-breakpoint
CREATE INDEX `ai_conv_user_id_idx` ON `ai_conversations` (`userId`);--> statement-breakpoint
CREATE INDEX `ai_conv_session_id_idx` ON `ai_conversations` (`sessionId`);--> statement-breakpoint
CREATE INDEX `ai_messages_conversation_id_idx` ON `ai_messages` (`conversationId`);--> statement-breakpoint
CREATE INDEX `analysis_reports_session_id_idx` ON `analysis_reports` (`sessionId`);--> statement-breakpoint
CREATE INDEX `analysis_reports_market_id_idx` ON `analysis_reports` (`marketId`);--> statement-breakpoint
CREATE INDEX `analysis_reports_created_at_idx` ON `analysis_reports` (`createdAt`);--> statement-breakpoint
CREATE INDEX `api_cache_type_idx` ON `api_cache` (`cacheType`);--> statement-breakpoint
CREATE INDEX `api_cache_expires_idx` ON `api_cache` (`expiresAt`);--> statement-breakpoint
CREATE INDEX `api_call_logs_provider_idx` ON `api_call_logs` (`provider`);--> statement-breakpoint
CREATE INDEX `api_call_logs_created_at_idx` ON `api_call_logs` (`createdAt`);--> statement-breakpoint
CREATE INDEX `api_call_logs_source_idx` ON `api_call_logs` (`source`);--> statement-breakpoint
CREATE INDEX `api_usage_date_provider_idx` ON `api_usage_summary` (`date`,`provider`);--> statement-breakpoint
CREATE INDEX `bug_reports_status_idx` ON `bug_reports` (`status`);--> statement-breakpoint
CREATE INDEX `bug_reports_priority_idx` ON `bug_reports` (`priority`);--> statement-breakpoint
CREATE INDEX `deal_alert_user_id_idx` ON `deal_alert_criteria` (`userId`);--> statement-breakpoint
CREATE INDEX `deal_alert_email_idx` ON `deal_alert_criteria` (`email`);--> statement-breakpoint
CREATE INDEX `deal_alert_city_state_idx` ON `deal_alert_criteria` (`city`,`state`);--> statement-breakpoint
CREATE INDEX `deal_alert_is_active_idx` ON `deal_alert_criteria` (`isActive`);--> statement-breakpoint
CREATE INDEX `deal_matches_criteria_id_idx` ON `deal_alert_matches` (`criteriaId`);--> statement-breakpoint
CREATE INDEX `deal_matches_status_idx` ON `deal_alert_matches` (`status`);--> statement-breakpoint
CREATE INDEX `deep_analysis_report_id_idx` ON `deep_analysis` (`reportId`);--> statement-breakpoint
CREATE INDEX `deep_analysis_status_idx` ON `deep_analysis` (`status`);--> statement-breakpoint
CREATE INDEX `email_optins_email_idx` ON `email_optins` (`email`);--> statement-breakpoint
CREATE INDEX `email_optins_is_active_idx` ON `email_optins` (`isActive`);--> statement-breakpoint
CREATE INDEX `email_optins_city_state_idx` ON `email_optins` (`city`,`state`);--> statement-breakpoint
CREATE INDEX `fav_listings_user_id_idx` ON `favorite_listings` (`userId`);--> statement-breakpoint
CREATE INDEX `fav_listings_session_id_idx` ON `favorite_listings` (`sessionId`);--> statement-breakpoint
CREATE INDEX `fav_listings_listing_id_idx` ON `favorite_listings` (`listingId`);--> statement-breakpoint
CREATE INDEX `fav_markets_user_id_idx` ON `favorite_markets` (`userId`);--> statement-breakpoint
CREATE INDEX `fav_markets_session_id_idx` ON `favorite_markets` (`sessionId`);--> statement-breakpoint
CREATE INDEX `fav_markets_market_id_idx` ON `favorite_markets` (`marketId`);--> statement-breakpoint
CREATE INDEX `fav_props_user_id_idx` ON `favorite_properties` (`userId`);--> statement-breakpoint
CREATE INDEX `fav_props_session_id_idx` ON `favorite_properties` (`sessionId`);--> statement-breakpoint
CREATE INDEX `fav_props_market_id_idx` ON `favorite_properties` (`marketId`);--> statement-breakpoint
CREATE INDEX `leads_email_idx` ON `leads` (`email`);--> statement-breakpoint
CREATE INDEX `leads_status_idx` ON `leads` (`status`);--> statement-breakpoint
CREATE INDEX `leads_created_at_idx` ON `leads` (`createdAt`);--> statement-breakpoint
CREATE INDEX `link_clicks_link_id_idx` ON `link_clicks` (`linkId`);--> statement-breakpoint
CREATE INDEX `market_alerts_user_id_idx` ON `market_alerts` (`userId`);--> statement-breakpoint
CREATE INDEX `market_alerts_market_id_idx` ON `market_alerts` (`marketId`);--> statement-breakpoint
CREATE INDEX `market_alerts_is_active_idx` ON `market_alerts` (`isActive`);--> statement-breakpoint
CREATE INDEX `market_eval_user_id_idx` ON `market_evaluations` (`userId`);--> statement-breakpoint
CREATE INDEX `market_eval_session_id_idx` ON `market_evaluations` (`sessionId`);--> statement-breakpoint
CREATE INDEX `market_eval_city_state_idx` ON `market_evaluations` (`city`,`state`);--> statement-breakpoint
CREATE INDEX `market_eval_status_idx` ON `market_evaluations` (`status`);--> statement-breakpoint
CREATE INDEX `newsletter_deals_city_id_idx` ON `newsletter_deals` (`cityId`);--> statement-breakpoint
CREATE INDEX `newsletter_deals_status_idx` ON `newsletter_deals` (`status`);--> statement-breakpoint
CREATE INDEX `newsletter_sends_contact_id_idx` ON `newsletter_sends` (`hubspotContactId`);--> statement-breakpoint
CREATE INDEX `newsletter_sends_email_idx` ON `newsletter_sends` (`email`);--> statement-breakpoint
CREATE INDEX `newsletter_sends_status_idx` ON `newsletter_sends` (`status`);--> statement-breakpoint
CREATE INDEX `notif_analytics_share_code_idx` ON `notification_analytics` (`shareCode`);--> statement-breakpoint
CREATE INDEX `notif_analytics_status_idx` ON `notification_analytics` (`status`);--> statement-breakpoint
CREATE INDEX `notif_analytics_created_at_idx` ON `notification_analytics` (`createdAt`);--> statement-breakpoint
CREATE INDEX `notifications_user_id_idx` ON `notifications` (`userId`);--> statement-breakpoint
CREATE INDEX `notifications_is_read_idx` ON `notifications` (`isRead`);--> statement-breakpoint
CREATE INDEX `notifications_created_at_idx` ON `notifications` (`createdAt`);--> statement-breakpoint
CREATE INDEX `promo_recipients_promo_id_idx` ON `promotion_recipients` (`promotionId`);--> statement-breakpoint
CREATE INDEX `promo_recipients_email_idx` ON `promotion_recipients` (`email`);--> statement-breakpoint
CREATE INDEX `reg_comments_user_id_idx` ON `regulation_comments` (`userId`);--> statement-breakpoint
CREATE INDEX `reg_comments_location_key_idx` ON `regulation_comments` (`locationKey`);--> statement-breakpoint
CREATE INDEX `saved_regs_user_id_idx` ON `saved_regulations` (`userId`);--> statement-breakpoint
CREATE INDEX `saved_regs_location_key_idx` ON `saved_regulations` (`locationKey`);--> statement-breakpoint
CREATE INDEX `saved_searches_user_id_idx` ON `saved_searches` (`userId`);--> statement-breakpoint
CREATE INDEX `saved_searches_session_id_idx` ON `saved_searches` (`sessionId`);--> statement-breakpoint
CREATE INDEX `saved_searches_search_type_idx` ON `saved_searches` (`searchType`);--> statement-breakpoint
CREATE INDEX `tool_usage_email_idx` ON `tool_usage_events` (`email`);--> statement-breakpoint
CREATE INDEX `tool_usage_session_id_idx` ON `tool_usage_events` (`sessionId`);--> statement-breakpoint
CREATE INDEX `tool_usage_user_id_idx` ON `tool_usage_events` (`userId`);--> statement-breakpoint
CREATE INDEX `tool_usage_event_type_idx` ON `tool_usage_events` (`eventType`);--> statement-breakpoint
CREATE INDEX `tool_usage_created_at_idx` ON `tool_usage_events` (`createdAt`);--> statement-breakpoint
CREATE INDEX `tool_usage_city_state_idx` ON `tool_usage_events` (`city`,`state`);--> statement-breakpoint
CREATE INDEX `universal_reports_type_idx` ON `universal_shareable_reports` (`reportType`);--> statement-breakpoint
CREATE INDEX `universal_reports_created_at_idx` ON `universal_shareable_reports` (`createdAt`);--> statement-breakpoint
CREATE INDEX `user_usage_user_id_date_idx` ON `user_usage` (`userId`,`date`);--> statement-breakpoint
CREATE INDEX `user_usage_session_id_date_idx` ON `user_usage` (`sessionId`,`date`);--> statement-breakpoint
CREATE INDEX `user_usage_ip_date_idx` ON `user_usage` (`ipAddress`,`date`);