CREATE INDEX `market_research_status_idx` ON `market_research_reports` (`status`);--> statement-breakpoint
CREATE INDEX `market_research_user_id_idx` ON `market_research_reports` (`userId`);--> statement-breakpoint
CREATE INDEX `market_research_created_at_idx` ON `market_research_reports` (`createdAt`);--> statement-breakpoint
CREATE INDEX `personalized_links_email_idx` ON `personalized_links` (`email`);--> statement-breakpoint
CREATE INDEX `personalized_links_short_code_idx` ON `personalized_links` (`shortCode`);--> statement-breakpoint
CREATE INDEX `personalized_links_campaign_idx` ON `personalized_links` (`campaignType`);--> statement-breakpoint
CREATE INDEX `regulation_cache_expires_idx` ON `regulation_cache` (`expiresAt`);--> statement-breakpoint
CREATE INDEX `regulation_cache_status_idx` ON `regulation_cache` (`status`);--> statement-breakpoint
CREATE INDEX `shareable_reg_location_idx` ON `shareable_regulation_reports` (`locationKey`);--> statement-breakpoint
CREATE INDEX `shareable_reg_creator_idx` ON `shareable_regulation_reports` (`creatorUserId`);--> statement-breakpoint
CREATE INDEX `shareable_reg_created_at_idx` ON `shareable_regulation_reports` (`createdAt`);--> statement-breakpoint
CREATE INDEX `shared_reports_user_id_idx` ON `shared_reports` (`createdByUserId`);--> statement-breakpoint
CREATE INDEX `shared_reports_report_type_idx` ON `shared_reports` (`reportType`);--> statement-breakpoint
CREATE INDEX `shared_reports_created_at_idx` ON `shared_reports` (`createdAt`);--> statement-breakpoint
CREATE INDEX `user_sessions_user_id_idx` ON `user_sessions` (`userId`);--> statement-breakpoint
CREATE INDEX `user_sessions_last_activity_idx` ON `user_sessions` (`lastActivityAt`);--> statement-breakpoint
CREATE INDEX `users_email_idx` ON `users` (`email`);--> statement-breakpoint
CREATE INDEX `users_role_idx` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `users_created_at_idx` ON `users` (`createdAt`);