export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  airdnaApiKey: process.env.AIRDNA_API_KEY ?? "",
  anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  coachinayahEmail: process.env.COACHINAYAH_EMAIL ?? "",
  coachinayahPassword: process.env.COACHINAYAH_PASSWORD ?? "",
  hasdataApiKey: process.env.HASDATA_API_KEY ?? "",
  rentometerApiKey: process.env.RENTOMETER_API_KEY ?? "",
  simpletextingApiKey: process.env.SIMPLETEXTING_API_KEY ?? "",
  zapierWebhookUrl: process.env.ZAPIER_WEBHOOK_URL ?? "",
  webinarjamApiKey: process.env.WEBINARJAM_API_KEY ?? "",
  hubspotApiKey: process.env.HUBSPOT_API_KEY ?? "",
  golpoApiKey: process.env.GOLPO_API_KEY ?? "",
  googleCalendarServiceAccountJson: process.env.GOOGLE_CALENDAR_SERVICE_ACCOUNT_JSON ?? "",
  googleCalendarImpersonateEmail: process.env.GOOGLE_CALENDAR_IMPERSONATE_EMAIL ?? "",
  devMockApi: process.env.DEV_MOCK_API === "true",
};
