import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, 
  Building2, 
  TrendingUp, 
  Loader2, 
  ChevronDown,
  ChevronUp,
  FileText,
  BarChart3,
  Target,
  AlertTriangle,
  CheckCircle2,
  Info,
  RefreshCw,
  ServerCrash
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { Streamdown } from 'streamdown';
import { trpc } from '@/lib/trpc';

interface AIAdvisorStepProps {
  // Property data
  property: {
    address: string;
    city: string;
    state: string;
    zipCode: string;
    bedrooms: number;
    bathrooms: number;
    accommodates: number;
    monthlyRent?: number;
    latitude?: number;
    longitude?: number;
  };
  // Revenue projections
  revenue: {
    projected: number;
    low: number;
    high: number;
    adr: number;
    occupancy: number;
    revpar: number;
  };
  // Cash flow analysis
  cashFlow?: {
    monthlyRevenue: number;
    monthlyRent: number;
    monthlyProfit: number;
    annualProfit: number;
    profitMargin: number;
    breakEvenOccupancy: number;
  };
  // All comparables
  comparables: Array<{
    title: string;
    bedrooms: number;
    bathrooms: number;
    accommodates: number;
    revenue: number;
    adr: number;
    occupancy: number;
    revpar: number;
    rating: number;
    reviews: number;
    distanceMeters?: number;
    isSuperhost?: boolean;
    isProfessionallyManaged?: boolean;
    propertyType?: string;
    amenities?: string[];
    lastReviewDate?: string;
    listingUrl?: string;
    photoCount?: number;
  }>;
  // Market insights
  marketInsights: {
    professionallyManagedPct: number;
    superhostPct: number;
    avgRating: number;
    totalListings: number;
    marketScore: number;
    investabilityScore?: number;
    rentalDemandScore?: number;
    revenueGrowthScore?: number;
    seasonalityScore?: number;
    regulationScore?: number;
  };
  // Historical data
  historicalData: {
    yoyChange: number;
    trend: 'up' | 'down' | 'stable';
    months: Array<{
      date: string;
      revenue: number;
      occupancy: number;
      adr: number;
      revpar: number;
      listingCount?: number;
    }>;
  };
  // Seasonality
  seasonality: Array<{
    month: string;
    revenue: number;
    adr: number;
    occupancy: number;
    revpar: number;
    yoyChange?: number;
  }>;
  // Market grade
  marketGrade: {
    grade: string;
    score: number;
    description: string;
    factors: Array<{
      name: string;
      score: number;
      weight: number;
    }>;
  };
  // Market position
  marketPosition: {
    percentile: number;
    rank: number;
    totalListings: number;
    vsAverage: number;
  };
  // Market data for market advisor
  marketData?: {
    name: string;
    city: string;
    state: string;
    country: string;
    scores: {
      marketScore: number;
      investabilityScore: number;
      rentalDemandScore: number;
      revenueGrowthScore: number;
      seasonalityScore: number;
      regulationScore: number;
    };
    metrics: {
      avgRevenue: number;
      avgOccupancy: number;
      avgAdr: number;
      avgRevpar: number;
      totalListings: number;
      professionallyManagedPct: number;
      superhostPct: number;
      avgRating: number;
    };
    revenueByBedroom: Array<{
      bedrooms: number;
      avgRevenue: number;
      avgOccupancy: number;
      avgAdr: number;
      listingCount: number;
    }>;
    topPerformers: Array<{
      title: string;
      bedrooms: number;
      bathrooms: number;
      revenue: number;
      occupancy: number;
      adr: number;
      rating: number;
      reviews: number;
      isSuperhost: boolean;
      isProfessionallyManaged: boolean;
    }>;
  };
}

export function AIAdvisorStep(props: AIAdvisorStepProps) {
  const [activeTab, setActiveTab] = useState<'property' | 'market'>('property');
  const [propertyAdvice, setPropertyAdvice] = useState<string | null>(null);
  const [marketAdvice, setMarketAdvice] = useState<string | null>(null);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [propertyAnalysisState, setPropertyAnalysisState] = useState<{
    startTime: number | null;
    elapsedSeconds: number;
    isTakingLong: boolean;
  }>({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
  const [marketAnalysisState, setMarketAnalysisState] = useState<{
    startTime: number | null;
    elapsedSeconds: number;
    isTakingLong: boolean;
  }>({ startTime: null, elapsedSeconds: 0, isTakingLong: false });

  const propertyAdvisorMutation = trpc.advanced.propertyAdvisorMax.useMutation();
  const marketAdvisorMutation = trpc.advanced.marketAdvisorMax.useMutation();

  // Auto-generate property analysis on mount (single-button flow)
  useEffect(() => {
    if (!hasAutoGenerated && !propertyAdvice && !propertyAdvisorMutation.isPending) {
      setHasAutoGenerated(true);
      handleGeneratePropertyAdvice();
    }
  }, [hasAutoGenerated, propertyAdvice, propertyAdvisorMutation.isPending]);

  const handleCancelPropertyAnalysis = () => {
    propertyAdvisorMutation.reset();
    setPropertyAnalysisState({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
  };

  const handleCancelMarketAnalysis = () => {
    marketAdvisorMutation.reset();
    setMarketAnalysisState({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
  };

  const handleGeneratePropertyAdvice = async () => {
    const startTime = Date.now();
    setPropertyAnalysisState({ startTime, elapsedSeconds: 0, isTakingLong: false });
    
    // Track elapsed time
    const elapsedInterval = setInterval(() => {
      setPropertyAnalysisState(prev => {
        if (!prev.startTime) return prev;
        const elapsed = Math.floor((Date.now() - prev.startTime) / 1000);
        const isTakingLong = elapsed >= 30; // Show warning after 30 seconds
        return { ...prev, elapsedSeconds: elapsed, isTakingLong };
      });
    }, 1000);
    
    try {
      const result = await propertyAdvisorMutation.mutateAsync({
        property: props.property,
        revenue: props.revenue,
        cashFlow: props.cashFlow,
        comparables: props.comparables,
        marketInsights: props.marketInsights,
        historicalData: props.historicalData,
        seasonality: props.seasonality,
        marketGrade: props.marketGrade,
        marketPosition: props.marketPosition,
      });
      
      clearInterval(elapsedInterval);
      setPropertyAnalysisState({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
      
      if (result.success && result.data?.advice) {
        setPropertyAdvice(result.data.advice);
      }
    } catch (error) {
      clearInterval(elapsedInterval);
      setPropertyAnalysisState({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
      console.error('Error generating property advice:', error);
    }
  };

  const handleGenerateMarketAdvice = async () => {
    if (!props.marketData) return;
    
    const startTime = Date.now();
    setMarketAnalysisState({ startTime, elapsedSeconds: 0, isTakingLong: false });
    
    // Track elapsed time
    const elapsedInterval = setInterval(() => {
      setMarketAnalysisState(prev => {
        if (!prev.startTime) return prev;
        const elapsed = Math.floor((Date.now() - prev.startTime) / 1000);
        const isTakingLong = elapsed >= 30; // Show warning after 30 seconds
        return { ...prev, elapsedSeconds: elapsed, isTakingLong };
      });
    }, 1000);
    
    try {
      const result = await marketAdvisorMutation.mutateAsync({
        market: {
          name: props.marketData.name,
          city: props.marketData.city,
          state: props.marketData.state,
          country: props.marketData.country,
        },
        scores: props.marketData.scores,
        metrics: props.marketData.metrics,
        revenueByBedroom: props.marketData.revenueByBedroom,
        historicalData: props.historicalData,
        seasonality: props.seasonality,
        topPerformers: props.marketData.topPerformers,
      });
      
      clearInterval(elapsedInterval);
      setMarketAnalysisState({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
      
      if (result.success && result.data?.advice) {
        setMarketAdvice(result.data.advice);
      }
    } catch (error) {
      clearInterval(elapsedInterval);
      setMarketAnalysisState({ startTime: null, elapsedSeconds: 0, isTakingLong: false });
      console.error('Error generating market advice:', error);
    }
  };

  const toggleSection = (section: string) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-amber-100 to-amber-200 rounded-2xl mb-4">
          <Sparkles className="w-8 h-8 text-amber-600" />
        </div>
        <h2 className="text-3xl font-bold text-slate-900">AI Advisor</h2>
        <p className="text-slate-600 max-w-2xl mx-auto">
          Get comprehensive, AI-powered analysis of your property or market. 
          Our advisor synthesizes all available data into actionable insights.
        </p>
      </div>

      {/* Advisor Tabs */}
      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as 'property' | 'market')} className="w-full">
        <TabsList className="grid w-full grid-cols-2 mb-6">
          <TabsTrigger value="property" className="flex items-center gap-2">
            <Building2 className="w-4 h-4" />
            Property Advisor
          </TabsTrigger>
          <TabsTrigger value="market" className="flex items-center gap-2">
            <TrendingUp className="w-4 h-4" />
            Market Advisor
          </TabsTrigger>
        </TabsList>

        {/* Property Advisor Tab */}
        <TabsContent value="property" className="space-y-6">
          <Card className="border-2 border-amber-200 bg-gradient-to-br from-amber-50 to-white">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <Building2 className="w-5 h-5 text-amber-600" />
                    Property Analysis
                  </CardTitle>
                  <CardDescription className="mt-1">
                    Comprehensive analysis of {props.property.address}
                  </CardDescription>
                </div>
                <Badge variant="outline" className="bg-amber-100 text-amber-700 border-amber-300">
                  {props.property.bedrooms} BR / {props.property.bathrooms} BA
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Property Summary */}
              <div className="grid grid-cols-3 gap-4 p-4 bg-white rounded-lg border border-amber-100">
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="text-center cursor-help">
                        <div className="text-lg font-bold text-slate-900">
                          {formatCurrency(props.revenue.projected)}
                        </div>
                        <div className="text-xs text-slate-600 flex items-center justify-center gap-1">
                          Projected Revenue <Info className="w-3 h-3 text-slate-400" />
                        </div>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent className="max-w-xs">
                      <p className="text-sm">Estimated annual income this property could generate based on comparable properties in your area. This is calculated from actual performance data of similar listings.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="text-center border-x border-amber-100 cursor-help">
                        <div className="text-lg font-bold text-slate-900">
                          {(props.revenue.occupancy > 1 ? props.revenue.occupancy : props.revenue.occupancy * 100).toFixed(0)}%
                        </div>
                        <div className="text-xs text-slate-600 flex items-center justify-center gap-1">
                          Occupancy <Info className="w-3 h-3 text-slate-400" />
                        </div>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent className="max-w-xs">
                      <p className="text-sm">The percentage of nights your property is expected to be booked throughout the year. Higher occupancy means more consistent bookings but may require competitive pricing.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="text-center cursor-help">
                        <div className="text-lg font-bold text-slate-900">
                          {formatCurrency(props.revenue.adr)}
                        </div>
                        <div className="text-xs text-slate-600 flex items-center justify-center gap-1">
                          Avg Daily Rate <Info className="w-3 h-3 text-slate-400" />
                        </div>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent className="max-w-xs">
                      <p className="text-sm">The average nightly price guests pay to stay at similar properties. This is what you could charge per night based on market data.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </div>

              {/* Generate Button */}
              {!propertyAdvice && (
                <div className="space-y-3">
                  <Button
                    onClick={handleGeneratePropertyAdvice}
                    disabled={propertyAdvisorMutation.isPending}
                    className="w-full bg-amber-600 hover:bg-amber-700 text-white py-6 text-lg"
                  >
                    {propertyAdvisorMutation.isPending ? (
                      <>
                        <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                        Analyzing Property Data... {propertyAnalysisState.elapsedSeconds > 0 && `(${propertyAnalysisState.elapsedSeconds}s)`}
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-5 h-5 mr-2" />
                        Generate Property Analysis
                      </>
                    )}
                  </Button>
                  
                  {/* Timeout Warning */}
                  {propertyAdvisorMutation.isPending && propertyAnalysisState.isTakingLong && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="p-3 bg-amber-50 rounded-lg border border-amber-200"
                    >
                      <div className="flex items-start gap-2">
                        <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                          <p className="text-sm font-medium text-amber-800">This is taking longer than expected...</p>
                          <p className="text-xs text-amber-700 mt-1">The AI is processing your property data. You can continue waiting or cancel and try again.</p>
                        </div>
                      </div>
                      <div className="flex gap-2 mt-2">
                        <Button
                          onClick={handleCancelPropertyAnalysis}
                          size="sm"
                          variant="outline"
                          className="border-amber-300 text-amber-700 hover:bg-amber-100"
                        >
                          Cancel Analysis
                        </Button>
                      </div>
                    </motion.div>
                  )}
                </div>
              )}

              {/* Error State with Retry */}
              {propertyAdvisorMutation.isError && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-5 bg-gradient-to-r from-red-50 to-orange-50 border border-red-200 rounded-xl shadow-sm"
                >
                  <div className="flex items-start gap-4">
                    <div className="p-2 bg-red-100 rounded-lg">
                      <ServerCrash className="w-6 h-6 text-red-500" />
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-red-800 mb-1">Property Analysis Failed</div>
                      <div className="text-sm text-red-600 mb-3">
                        {propertyAdvisorMutation.error?.message?.includes('timeout') || propertyAdvisorMutation.error?.message?.includes('network')
                          ? 'Network connection issue. Please check your internet connection and try again.'
                          : propertyAdvisorMutation.error?.message?.includes('rate limit')
                          ? 'Too many requests. Please wait a moment and try again.'
                          : 'Unable to generate property analysis. This could be due to a temporary service issue.'}
                      </div>
                      <Button
                        onClick={() => {
                          propertyAdvisorMutation.reset();
                          handleGeneratePropertyAdvice();
                        }}
                        size="sm"
                        className="bg-red-600 hover:bg-red-700 text-white"
                      >
                        <RefreshCw className="w-4 h-4 mr-2" />
                        Try Again
                      </Button>
                    </div>
                  </div>
                  <div className="mt-3 pt-3 border-t border-red-200">
                    <p className="text-xs text-red-500 flex items-center gap-1">
                      <Info className="w-3 h-3" />
                      If the problem persists, try refreshing the page or contact support.
                    </p>
                  </div>
                </motion.div>
              )}

              {/* Analysis Result */}
              {propertyAdvice && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-4"
                >
                  <div className="flex items-center gap-2 text-green-600">
                    <CheckCircle2 className="w-5 h-5" />
                    <span className="font-medium">Analysis Complete</span>
                  </div>
                  
                  <div className="prose prose-slate max-w-none bg-white rounded-lg border border-slate-200 p-6">
                    <Streamdown>{propertyAdvice}</Streamdown>
                  </div>

                  <Button
                    onClick={() => setPropertyAdvice(null)}
                    variant="outline"
                    className="w-full"
                  >
                    Generate New Analysis
                  </Button>
                </motion.div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Market Advisor Tab */}
        <TabsContent value="market" className="space-y-6">
          <Card className="border-2 border-blue-200 bg-gradient-to-br from-blue-50 to-white">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <TrendingUp className="w-5 h-5 text-blue-600" />
                    Market Analysis
                  </CardTitle>
                  <CardDescription className="mt-1">
                    Comprehensive analysis of {props.marketData?.name || `${props.property.city}, ${props.property.state}`}
                  </CardDescription>
                </div>
                <Badge variant="outline" className="bg-blue-100 text-blue-700 border-blue-300">
                  Grade: {props.marketGrade.grade}
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Market Summary */}
              <div className="grid grid-cols-3 gap-4 p-4 bg-white rounded-lg border border-blue-100">
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="text-center cursor-help">
                        <div className="text-lg font-bold text-slate-900">
                          {props.marketInsights.totalListings.toLocaleString()}
                        </div>
                        <div className="text-xs text-slate-600 flex items-center justify-center gap-1">
                          Total Listings <Info className="w-3 h-3 text-slate-400" />
                        </div>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent className="max-w-xs">
                      <p className="text-sm">The total number of active short-term rental listings in this market. More listings can mean more competition, but also indicates proven demand.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="text-center border-x border-blue-100 cursor-help">
                        <div className="text-lg font-bold text-slate-900">
                          {props.marketGrade.score}/100
                        </div>
                        <div className="text-xs text-slate-600 flex items-center justify-center gap-1">
                          Market Score <Info className="w-3 h-3 text-slate-400" />
                        </div>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent className="max-w-xs">
                      <p className="text-sm">An overall score (0-100) measuring this market's attractiveness for short-term rentals. Higher scores indicate stronger rental demand, better revenue potential, and favorable market conditions.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <div className="text-center cursor-help">
                        <div className={`text-lg font-bold ${props.historicalData.yoyChange >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                          {props.historicalData.yoyChange >= 0 ? '+' : ''}{props.historicalData.yoyChange.toFixed(1)}%
                        </div>
                        <div className="text-xs text-slate-600 flex items-center justify-center gap-1">
                          YoY Change <Info className="w-3 h-3 text-slate-400" />
                        </div>
                      </div>
                    </TooltipTrigger>
                    <TooltipContent className="max-w-xs">
                      <p className="text-sm">Year-over-Year revenue change comparing this year to last year. Green (positive) means the market is growing; Red (negative) means revenue is declining.</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </div>

              {/* Generate Button */}
              {!marketAdvice && (
                <div className="space-y-3">
                  <Button
                    onClick={handleGenerateMarketAdvice}
                    disabled={marketAdvisorMutation.isPending || !props.marketData}
                    className="w-full bg-blue-600 hover:bg-blue-700 text-white py-6 text-lg"
                  >
                    {marketAdvisorMutation.isPending ? (
                      <>
                        <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                        Analyzing Market Data... {marketAnalysisState.elapsedSeconds > 0 && `(${marketAnalysisState.elapsedSeconds}s)`}
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-5 h-5 mr-2" />
                        Generate Market Analysis
                      </>
                    )}
                  </Button>
                  
                  {/* Timeout Warning */}
                  {marketAdvisorMutation.isPending && marketAnalysisState.isTakingLong && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="p-3 bg-amber-50 rounded-lg border border-amber-200"
                    >
                      <div className="flex items-start gap-2">
                        <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                          <p className="text-sm font-medium text-amber-800">This is taking longer than expected...</p>
                          <p className="text-xs text-amber-700 mt-1">The AI is processing market data. You can continue waiting or cancel and try again.</p>
                        </div>
                      </div>
                      <div className="flex gap-2 mt-2">
                        <Button
                          onClick={handleCancelMarketAnalysis}
                          size="sm"
                          variant="outline"
                          className="border-amber-300 text-amber-700 hover:bg-amber-100"
                        >
                          Cancel Analysis
                        </Button>
                      </div>
                    </motion.div>
                  )}
                </div>
              )}

              {!props.marketData && (
                <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg flex items-start gap-3">
                  <Info className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
                  <div>
                    <div className="font-medium text-blue-800">Market Data Required</div>
                    <div className="text-sm text-blue-600">
                      Complete market data is needed for full market analysis. 
                      The property analysis is available with current data.
                    </div>
                  </div>
                </div>
              )}

              {/* Error State with Retry */}
              {marketAdvisorMutation.isError && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-5 bg-gradient-to-r from-red-50 to-orange-50 border border-red-200 rounded-xl shadow-sm"
                >
                  <div className="flex items-start gap-4">
                    <div className="p-2 bg-red-100 rounded-lg">
                      <ServerCrash className="w-6 h-6 text-red-500" />
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-red-800 mb-1">Market Analysis Failed</div>
                      <div className="text-sm text-red-600 mb-3">
                        {marketAdvisorMutation.error?.message?.includes('timeout') || marketAdvisorMutation.error?.message?.includes('network')
                          ? 'Network connection issue. Please check your internet connection and try again.'
                          : marketAdvisorMutation.error?.message?.includes('rate limit')
                          ? 'Too many requests. Please wait a moment and try again.'
                          : 'Unable to generate market analysis. This could be due to a temporary service issue.'}
                      </div>
                      <Button
                        onClick={() => {
                          marketAdvisorMutation.reset();
                          handleGenerateMarketAdvice();
                        }}
                        size="sm"
                        className="bg-red-600 hover:bg-red-700 text-white"
                      >
                        <RefreshCw className="w-4 h-4 mr-2" />
                        Try Again
                      </Button>
                    </div>
                  </div>
                  <div className="mt-3 pt-3 border-t border-red-200">
                    <p className="text-xs text-red-500 flex items-center gap-1">
                      <Info className="w-3 h-3" />
                      If the problem persists, try refreshing the page or contact support.
                    </p>
                  </div>
                </motion.div>
              )}

              {/* Analysis Result */}
              {marketAdvice && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-4"
                >
                  <div className="flex items-center gap-2 text-green-600">
                    <CheckCircle2 className="w-5 h-5" />
                    <span className="font-medium">Analysis Complete</span>
                  </div>
                  
                  <div className="prose prose-slate max-w-none bg-white rounded-lg border border-slate-200 p-6">
                    <Streamdown>{marketAdvice}</Streamdown>
                  </div>

                  <Button
                    onClick={() => setMarketAdvice(null)}
                    variant="outline"
                    className="w-full"
                  >
                    Generate New Analysis
                  </Button>
                </motion.div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>


    </div>
  );
}

export default AIAdvisorStep;
